// Mock data for the operator UI prototype

const CLIENTS = [
  {
    slug: 'dan-balkun', name: 'Dan Balkun',
    company: 'Balkun Title & Closing',
    industry: 'Title / Closing', market: 'Providence, RI',
    tier: 'Standard', status: 'Active',
    photoCount: 8, audioCount: 1,
    lastVideo: '2 days ago',
    videosThisMonth: 3, videoQuota: 4,
    color: '#9B5CF6',
    initials: 'DB',
    assetDrive: 'drive.google.com/balkun-assets',
    format: '20s',
    brandPrimary: '#C0C0C0',
    brandAccent: '#1A1A1A',
  },
  {
    slug: 'james-duffer', name: 'James Duffer',
    company: 'Duffer Real Estate',
    industry: 'Real Estate', market: 'Smithfield, RI',
    tier: 'Premium', status: 'Active',
    photoCount: 6, audioCount: 2,
    lastVideo: '6 hrs ago',
    videosThisMonth: 4, videoQuota: 4,
    color: '#E8B860',
    initials: 'JD',
    assetDrive: 'drive.google.com/duffer-assets',
    format: '20s',
    brandPrimary: '#1F4E3D',
    brandAccent: '#D4AF5F',
  },
  {
    slug: 'evelyn-decosta', name: 'Evelyn DeCosta',
    company: 'Guaranteed Autosales',
    industry: 'Automotive', market: 'Cranston, RI',
    tier: 'Standard', status: 'In review',
    photoCount: 5, audioCount: 1,
    lastVideo: 'Just now',
    videosThisMonth: 2, videoQuota: 3,
    color: '#7CA7FF',
    initials: 'ED',
    assetDrive: 'drive.google.com/decosta-assets',
    format: '30s',
    brandPrimary: '#B91C1C',
    brandAccent: '#0A0A0A',
  },
  {
    slug: 'marco-rossi', name: 'Marco Rossi',
    company: 'Rossi Group Realty',
    industry: 'Real Estate', market: 'Hartford, CT',
    tier: 'Premium', status: 'Active',
    photoCount: 9, audioCount: 1,
    lastVideo: '1 wk ago',
    videosThisMonth: 1, videoQuota: 4,
    color: '#4FD68A',
    initials: 'MR',
    assetDrive: 'drive.google.com/rossi-assets',
    format: '30s',
    brandPrimary: '#7C2D12',
    brandAccent: '#F5E6D3',
  },
  {
    slug: 'priya-patel', name: 'Priya Patel',
    company: 'Patel & Co. Law',
    industry: 'Title / Closing', market: 'Columbus, OH',
    tier: 'Standard', status: 'Active',
    photoCount: 4, audioCount: 1,
    lastVideo: '3 days ago',
    videosThisMonth: 2, videoQuota: 3,
    color: '#F06571',
    initials: 'PP',
    assetDrive: 'drive.google.com/patel-assets',
    format: '20s',
    brandPrimary: '#0E4F88',
    brandAccent: '#F2C97A',
  },
  {
    slug: 'kelsey-nguyen', name: 'Kelsey Nguyen',
    company: 'Nguyen Homes Boston',
    industry: 'Real Estate', market: 'Boston, MA',
    tier: 'Premium', status: 'Onboarding',
    photoCount: 3, audioCount: 0,
    lastVideo: '—',
    videosThisMonth: 0, videoQuota: 4,
    color: '#B57CF8',
    initials: 'KN',
    assetDrive: 'drive.google.com/nguyen-assets',
    format: '30s',
    brandPrimary: '#1E293B',
    brandAccent: '#E8B860',
  },
];

// Recent / live jobs
const JOBS = [
  {
    id: 'job_48217', client: 'james-duffer',
    template: 'Market Minute', format: '20s',
    status: 'awaiting_approval', // awaiting_approval | rendering | done | failed | queued
    stage: 'clip_1_review',      // asset_upload | clip_1_gen | clip_1_review | clip_2_gen | assembly | done
    createdAt: '6 hrs ago',
    duration: 20, resolution: '720p',
    cost: 3.12, costProjected: 6.24,
    clipsDone: 1, clipsTotal: 2,
    prompt: 'James walks through a modern staged living room, stops, turns to camera and says "This 3-bed in Smithfield just hit market — and it won\'t last." Golden hour light, dolly in.',
    thumb: '#E8B860',
  },
  {
    id: 'job_48216', client: 'evelyn-decosta',
    template: 'Inventory Showcase', format: '30s',
    status: 'rendering',
    stage: 'clip_2_gen',
    createdAt: '12 min ago',
    duration: 30, resolution: '720p',
    cost: 3.04, costProjected: 9.10,
    clipsDone: 1, clipsTotal: 3,
    prompt: '@Image1 is Evelyn at Guaranteed Autosales lot. Scene 1: wide shot of the lot. Scene 2: close on 2016 Honda CR-V. Scene 3: Evelyn says "drive it home today."',
    thumb: '#7CA7FF',
  },
  {
    id: 'job_48215', client: 'dan-balkun',
    template: 'Closing Tip', format: '20s',
    status: 'done', stage: 'done',
    createdAt: '2 days ago',
    duration: 23, resolution: '720p',
    cost: 6.04, costProjected: 6.04,
    clipsDone: 2, clipsTotal: 2,
    prompt: 'Dan in charcoal suit, office setting, explains the 3 things every first-time buyer misses at closing.',
    thumb: '#9B5CF6',
  },
  {
    id: 'job_48214', client: 'marco-rossi',
    template: 'Neighborhood Spotlight', format: '30s',
    status: 'failed', stage: 'clip_2_gen',
    createdAt: '3 days ago',
    duration: 30, resolution: '720p',
    cost: 3.18, costProjected: 9.20,
    clipsDone: 1, clipsTotal: 3,
    failReason: 'Seed Dance moderation flagged scene 2 (exterior with people)',
    prompt: 'Marco walks through the West End of Hartford, pointing out local cafés and brownstones.',
    thumb: '#4FD68A',
  },
  {
    id: 'job_48213', client: 'priya-patel',
    template: 'Market Minute', format: '20s',
    status: 'done', stage: 'done',
    createdAt: '3 days ago',
    duration: 23, resolution: '720p',
    cost: 5.92, costProjected: 5.92,
    clipsDone: 2, clipsTotal: 2,
    prompt: 'Priya delivers a Columbus market update — median home price up 4% YoY.',
    thumb: '#F06571',
  },
  {
    id: 'job_48212', client: 'dan-balkun',
    template: 'Personal Brand', format: '20s',
    status: 'queued', stage: 'asset_upload',
    createdAt: 'queued',
    duration: 20, resolution: '720p',
    cost: 0, costProjected: 6.00,
    clipsDone: 0, clipsTotal: 2,
    prompt: 'Dan introduces himself and his 18 years in Rhode Island title law.',
    thumb: '#9B5CF6',
  },
];

// End-card pool per client
const END_CARDS = {
  'dan-balkun': [
    { id: 'ec_db_1', name: 'Signature Silver',    accent: '#C0C0C0', bg: '#0F0F12', layout: 'centered', motion: 'fade', usage: 14, lastUsed: '2d' },
    { id: 'ec_db_2', name: 'Closing Tips CTA',    accent: '#E8B860', bg: '#1B1514', layout: 'bar_cta',  motion: 'slide', usage: 6,  lastUsed: '5d' },
    { id: 'ec_db_3', name: 'Trust Mark Bold',     accent: '#9B5CF6', bg: '#0E0F13', layout: 'fullscreen_mark', motion: 'static', usage: 3, lastUsed: '9d' },
  ],
  'james-duffer': [
    { id: 'ec_jd_1', name: 'Open House Serif',    accent: '#D4AF5F', bg: '#1F4E3D', layout: 'split_hero', motion: 'kenburns', usage: 11, lastUsed: '6h' },
    { id: 'ec_jd_2', name: 'Just Listed Gold',    accent: '#D4AF5F', bg: '#0A0A0A', layout: 'centered',   motion: 'fade',     usage: 8,  lastUsed: '1d' },
  ],
  'evelyn-decosta': [
    { id: 'ec_ed_1', name: 'Drive It Home Red',   accent: '#B91C1C', bg: '#0A0A0A', layout: 'bar_cta', motion: 'slide', usage: 4, lastUsed: '1h' },
    { id: 'ec_ed_2', name: 'Inventory Grid',      accent: '#F2C97A', bg: '#121214', layout: 'centered', motion: 'fade', usage: 2, lastUsed: '5d' },
    { id: 'ec_ed_3', name: 'Lot Location Badge',  accent: '#B91C1C', bg: '#1A0F0F', layout: 'fullscreen_mark', motion: 'static', usage: 1, lastUsed: '2w' },
  ],
  'marco-rossi': [
    { id: 'ec_mr_1', name: 'Hartford Hero',       accent: '#F5E6D3', bg: '#7C2D12', layout: 'split_hero', motion: 'kenburns', usage: 5, lastUsed: '1w' },
    { id: 'ec_mr_2', name: 'Rossi Signature',     accent: '#F5E6D3', bg: '#0A0A0A', layout: 'centered', motion: 'fade', usage: 9, lastUsed: '3d' },
  ],
  'priya-patel': [
    { id: 'ec_pp_1', name: 'Patel & Co. Blue',    accent: '#F2C97A', bg: '#0E4F88', layout: 'centered', motion: 'fade', usage: 7, lastUsed: '3d' },
  ],
  'kelsey-nguyen': [],
};

// Cost roll-up (last 30 days)
const COST_SERIES = [
  3.1, 6.2, 0, 3.0, 9.1, 0, 0,
  6.0, 6.1, 3.0, 12.2, 6.3, 0, 3.0,
  9.1, 6.0, 6.1, 0, 3.0, 9.2, 6.0,
  3.1, 6.1, 12.0, 9.1, 6.0, 3.1, 6.0,
  9.2, 3.0,
];

const TEMPLATES = [
  { id: 't_market',  name: 'Market Minute',        duration: '20s', industries: ['Real Estate','Title / Closing'], icon: 'chart' },
  { id: 't_profile', name: 'Realtor / Agent Profile', duration: '20s', industries: ['Real Estate'], icon: 'user' },
  { id: 't_tip',     name: 'Closing Tip',          duration: '20s', industries: ['Title / Closing'], icon: 'bulb' },
  { id: 't_hood',    name: 'Neighborhood Spotlight', duration: '30s', industries: ['Real Estate'], icon: 'map' },
  { id: 't_tour',    name: 'Property Tour',        duration: '30s', industries: ['Real Estate'], icon: 'home' },
  { id: 't_inv',     name: 'Inventory Showcase',   duration: '30s', industries: ['Automotive'], icon: 'car' },
  { id: 't_holiday', name: 'Seasonal Greeting',    duration: '20s', industries: ['Real Estate','Title / Closing','Automotive'], icon: 'star' },
  { id: 't_custom',  name: 'Custom / Freeform',    duration: '20s', industries: ['Real Estate','Title / Closing','Automotive'], icon: 'plus' },
];

Object.assign(window, { CLIENTS, JOBS, END_CARDS, COST_SERIES, TEMPLATES });
